pub mod game_plugin_group;
mod player_plugin;
mod asset_plugin;
pub mod asteroid_plugin;
pub mod collision_plugin;
pub mod physics_plugin;
pub mod global_input_plugin;
pub mod screen_wrap_plugin;
pub mod game_schedule_plugin;
pub mod camera_plugin;
pub mod settings_plugin;
pub mod animation_plugin;